### PR TITLE
Committing auth change

### PR DESCRIPTION
**Pull request by makaveli0129**
## Pull Request Checklist

**Is this in reference to an existing issue?**

#### General

- [ ] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

### CODE REVIEW

**Comment by majormoses** [comment]
can you please fixup ci, add a changelog entry per: https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md and add a testing artifact per https://github.com/sensu-plugins/community/blob/master/PULL_REQUEST_PROCESS.md#7-testing-artifacts

**Comment by makaveli0129** [comment]
Before change:
```
/opt/sensu/embedded/bin/ruby ./check-sftp.rb -h hostname  -u username -s password -P 10022
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/cipher_factory.rb:97: warning: constant OpenSSL::Cipher::Cipher is deprecated
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/cipher_factory.rb:72: warning: constant OpenSSL::Cipher::Cipher is deprecated
CheckSftp CRITICAL: Failed authentication with username
```
After Change:
```
/opt/sensu/embedded/bin/ruby ./check-sftp.rb -h hostname  -u username -s password -P 10022
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/cipher_factory.rb:97: warning: constant OpenSSL::Cipher::Cipher is deprecated
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/cipher_factory.rb:72: warning: constant OpenSSL::Cipher::Cipher is deprecated
CheckSftp OK
```

**Review by majormoses — APPROVED** [review]
LGTM

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-sftp/versions/1.0.1

**Pull request merged**
